### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Tee Example",
  "email": "debbie@example.com",
  "password": "StrongPassword123"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}
