### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Micheal",
  "email": "micheal@example.com",
  "password": "StrongPassword123"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "tee@example.com",
  "password": "StrongPassword123"
}
